version: '3.3'
services:
  # nginx:
  #   image: webdevops/nginx
  #   container_name: nginx
  #   hostname: nginx
  #
  #   tty: true
  #   volumes:
  #     - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - .docker-volumes/nginx/logs:/var/log/nginx
  #     - .:/var/www/localhost/htdocs
  #   expose:
  #     - 80
  #   ports:
  #     - 8080:80
  #   extra_hosts:
  #     - host.docker.internal:host-gateway
  #   links:
  #     - application:application
  #
  #   networks:
  #     network:
  #       ipv4_address: 172.10.0.1
  # env_file:
  #     .docker/nginx/env

  laravel-startkit-api:
    image: macedodosanjosmateus/laravel-startkit:prd
    build:
      context: ./
      dockerfile: .docker/Dockerfile.prd
    container_name: laravel-startkit-api
    tty: true
    volumes:
      - .:/var/www/localhost/htdocs
    depends_on:
      - mysql
      - mongodb
      - rabbitmq
      - redis
      - localstack
    expose:
      - 80
      - 9000
    ports:
      - 8080:80
      - 9000:9000
    links:
      - mysql:mysql
      - mongodb:mongodb
      - rabbitmq:rabbitmq
      - redis:redis
      - localstack:localstack
    extra_hosts:
      - host.docker.internal:host-gateway
    hostname: laravel-startkit-api
    networks:
      network:
        ipv4_address: 172.10.0.2

  laravel-startkit-api-dev:
    image: macedodosanjosmateus/laravel-startkit:dev
    build:
      context: ./
      dockerfile: .docker/Dockerfile.dev
    container_name: laravel-startkit-api-dev
    tty: true
    volumes:
      - .:/var/www/localhost/htdocs
    depends_on:
      - mysql
      - mongodb
      - rabbitmq
      - redis
      - localstack
    expose:
      - 80
    ports:
      - 8081:80
    links:
      - mysql:mysql
      - mongodb:mongodb
      - rabbitmq:rabbitmq
      - redis:redis
      - localstack:localstack
    extra_hosts:
      - host.docker.internal:host-gateway
    hostname: laravel-startkit-api-dev
    networks:
      network:
        ipv4_address: 172.10.0.3
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE:-debug}
      XDEBUG_CLIENT_HOST: ${XDEBUG_CLIENT_HOST:-host.docker.internal}
      XDEBUG_CLIENT_PORT: ${XDEBUG_CLIENT_PORT:-9003}

  laravel-startkit-api-swl:
    image: macedodosanjosmateus/laravel-startkit:swl
    build:
      context: ./
      dockerfile: .docker/Dockerfile.swl
    container_name: laravel-startkit-api-swl
    tty: true
    volumes:
      - .:/var/www/localhost/htdocs
    depends_on:
      - mysql
      - mongodb
      - rabbitmq
      - redis
      - localstack
    expose:
      - 8000
      - 80
    ports:
      - 8000:8000
      - 8082:80
    links:
      - mysql:mysql
      - mongodb:mongodb
      - rabbitmq:rabbitmq
      - redis:redis
      - localstack:localstack
    extra_hosts:
      - host.docker.internal:host-gateway
    hostname: laravel-startkit-api-swl
    networks:
      network:
        ipv4_address: 172.10.0.4

  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - .docker-volumes/mysql:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 3306:3306
    extra_hosts:
      - host.docker.internal:host-gateway
    hostname: mysql
    networks:
      network:
        ipv4_address: 172.10.0.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel_startkit_api
      MYSQL_PASSWORD: Secret*123
      MYSQL_DB: laravel_startkit_api

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - .docker/mongodb:/docker-entrypoint-initdb.d
      - .docker-volumes/mongodb:/data/db
    ports:
      - 27017:27017
    extra_hosts:
      - host.docker.internal:host-gateway
    hostname: mongodb
    networks:
      network:
        ipv4_address: 172.10.0.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      # - .docker/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - .docker-volumes/rabbitmq:/var/lib/rabbitmq
    expose:
      - 5672
      - 15672
      - 25672
    ports:
      - 5672:5672
      - 25672:25672
      - 15672:15672
    hostname: rabbitmq
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      network:
        ipv4_address: 172.10.0.7

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --databases 2
    volumes:
      - .docker-volumes/redis/data:/data
    expose:
      - 6379
    ports:
      - 6379:6379
    hostname: redis
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      network:
        ipv4_address: 172.10.0.8

  localstack:
    image: localstack/localstack
    container_name: localstack
    volumes:
      - .docker-volumes/localstack/data:/tmp/localstack/data
      - /var/run/docker.sock:/var/run/docker.sock
      - .docker/localstack:/docker-entrypoint-initaws.d
    expose:
      - 4572
      - 4576
      - 4566
    ports:
      - 4572:4572 # s3
      - 4576:4576 # sqs
      - 4566:4566 # cli
    hostname: localstack
    extra_hosts:
      - host.docker.internal:host-gateway

    networks:
      network:
        ipv4_address: 172.10.0.9
    environment:
      SERVICES: s3,sqs
      DOCKER_HOST: unix:///var/run/docker.sock
      DEBUG: 1
      HOSTNAME_EXTERNAL: localstack

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/24
