apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laravel-startkit-pvc
  labels:
    app.kubernetes.io/name: laravel-startkit
    app.kubernetes.io/component: persistent-volume-claim
  annotations:
    app.kubernetes.io/name: laravel-startkit
    app.kubernetes.io/component: persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
