apiVersion: v1
kind: ServiceAccount
metadata:
  name: laravel-startkit-sa
  namespace: "default"
  labels:
    app.kubernetes.io/name: laravel-startkit
    app.kubernetes.io/component: service-account
  annotations:
    app.kubernetes.io/name: laravel-startkit
    app.kubernetes.io/component: service-account
secrets:
  - name: laravel-startkit-secrets
automountServiceAccountToken: true
