# Image
FROM macedodosanjosmateus/laravel-startkit:base
# Variables
USER root
ENV DOCUMENT_ROOT /var/www/localhost/htdocs
ENV XDEBUG_MODE=debug
ENV XDEBUG_CLIENT_HOST=host.docker.internal
ENV XDEBUG_CLIENT_PORT=9003

# Install dependencies
RUN apk add --no-cache \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && apk del --no-cache \
    gcc \
    g++ \
    make \
    perl \
    autoconf \
    dpkg-dev \
    dpkg \
    file \
    libc-dev \
    pkgconf \
    re2c

COPY .docker/nginx/nginx-dev.conf /etc/nginx/nginx.conf
COPY .docker/php/daemon-process-dev.conf /etc/supervisor/supervisord.conf
COPY .docker/php/php-dev.ini /usr/local/etc/php/conf.d/app.ini
COPY .docker/php/php-xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
COPY .docker/php/php-fpm-www.conf /usr/local/etc/php-fpm.d/www.conf

USER www-data
COPY app $DOCUMENT_ROOT/app
COPY src $DOCUMENT_ROOT/src
COPY config $DOCUMENT_ROOT/config